version: '3.3'

services:
  www:
    build: ./
    depends_on:
      - mysql
    container_name: www_books
    restart: always   
    ports:
      - '8000:8000'
    # dns:
    #   - 8.8.8.8
    volumes:
      - ./:/var/www/
    command: "symfony server:start"
    networks:
      - rr-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Port interface Web
    networks:
      - rr-net  # Nom du réseau Docker
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Books
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - rr-net

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  rr-net:
    driver: bridge

volumes:
  db-data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
